fix/update react 17
PayFit/react-big-calendar pull request #7
Opened 2022-12-20 14:46 UTC by nicolastoulemont

This update the package to react 17 and resolve the opening of the popup when running React v17

2022-12-20 19:21 UTC, soupette requested changes
Can you add the bundle.js and bundle.js.map to the .gitignore?

Also, why is there a diff in the fontawesome files?

Other than that good job you are a lifesaver on this one!

2022-12-21 08:23 UTC, nicolastoulemont commented
> Also, why is there a diff in the fontawesome files?

They're outputted by the `build:example` command which I re-ran to ensure that they're up to date. Not sure why they changed 🤔 
They're not included in the pkg anyway (only the lib folder is released)

2022-12-21 13:11 UTC, soupette commented on .gitignore
> +examples/bundle.js
Can you delete the bundle.js and bundle.js.map too so we don't have them in the history?

2022-12-21 13:14 UTC, nicolastoulemont commented on .gitignore
> +examples/bundle.js
They've been deleted as well

2022-12-21 17:38 UTC, soupette approved these changes
LGTM

2022-12-22 08:05 UTC, merged